Repository spacetelescope/catkit2, pull requests merged in 2024-06, with the labels that each got.

#212 Add informations about needing to create an environment variable in the Thorlabs Cubes service doc
  docs/services/thorlabs_cube_motor_kinesis.rst
Labels: documentation, collaborators

#213 Add or fix missing service docs
  docs/index.rst
  docs/services/safety_manual_check.rst
Labels: documentation

#214 Add stages models to the thorlabs kinesis motors service
  catkit2/services/thorlabs_cube_motor_kinesis/thorlabs_cube_motor_kinesis.py
Labels: enhancement, hardware, collaborators

#215 Fix Thorlabs Cube motors size of serial number's list
  catkit2/services/thorlabs_cube_motor_kinesis/thorlabs_cube_motor_kinesis.py
Labels: enhancement, hardware, collaborators

#221 Bugfix/piezo voltage limits datastream
  catkit2/services/ni_daq/ni_daq.py
  catkit2/services/ni_daq_sim/ni_daq_sim.py
Labels: bugfix
