Repository spacetelescope/catkit2, pull requests merged in 2024-09, with the labels that each got.

#204 Add performance tracing
  catkit2/testbed/__init__.py
  catkit2/testbed/distributor.py
  catkit2/testbed/logging.py
  catkit2/testbed/testbed.py
  catkit2/testbed/tracing.py
  catkit_bindings/bindings.cpp
  catkit_core/CMakeLists.txt
  catkit_core/DataStream.cpp
  catkit_core/Service.cpp
  catkit_core/Tracing.cpp
  catkit_core/Tracing.h
  catkit_core/TracingProxy.cpp
  catkit_core/TracingProxy.h
  proto/tracing.proto
  tests/test_tracing.py
Labels: enhancement

#243 Refactor the MCLS1 service
  catkit2/services/thorlabs_mcls1/thorlabs_mcls1.py
Labels: refactor

#245 Add CPU affinity and process priority control
  catkit2/testbed/testbed.py
Labels: enhancement

#242 Bugfix/mcls1 sim
  catkit2/services/thorlabs_mcls1_sim/thorlabs_mcls1_sim.py
  catkit2/simulator/simulator.py
Labels: bugfix, refactor

#244 Add trace intervals for several services
  catkit2/services/bmc_dm/bmc_dm.py
  catkit2/services/flir_camera/flir_camera.py
  catkit2/services/zwo_camera/zwo_camera.py
Labels: enhancement
