Repository spacetelescope/catkit2, pull requests merged in 2024-10, with the labels that each got.

#156 Add DM base class.
  catkit2/base_services/bmc_deformable_mirror.py
  catkit2/base_services/deformable_mirror.py
  catkit2/services/bmc_deformable_mirror_hardware/bmc_deformable_mirror_hardware.py
  catkit2/services/bmc_deformable_mirror_sim/bmc_deformable_mirror_sim.py
  catkit2/testbed/proxies/__init__.py
  catkit2/testbed/proxies/deformable_mirror.py
  docs/index.rst
  docs/services/bmc_deformable_mirror.rst
  docs/services/bmc_dm.rst
  docs/services/deformable_mirror.rst
Labels: refactor

#252 Feature/steiger service docs round2
  docs/services/camera_sim.rst
  docs/services/thorlabs_fw102c.rst
  docs/services/thorlabs_mff101.rst
  docs/services/thorlabs_tsp01.rst
Labels: documentation

#257 Remove VimbaPython dependency from environment.yml
  environment.yml
Labels: infrastructure

#260 Make DM map and command functions to outside of ServiceProxy.
  catkit2/testbed/proxies/deformable_mirror.py
Labels: enhancement
