Repository spacetelescope/catkit2, pull requests merged in 2024-07, with the labels that each got.

#222 Modify Allied Vision Camera service to make it work with the new VimbaX software
  catkit2/services/allied_vision_camera/allied_vision_camera.py
  docs/services/allied_vision_camera.rst
Labels: enhancement

#224 Service docs work (Steiger)
  docs/services/bmc_dm.rst
  docs/services/flir_camera.rst
  docs/services/nkt_superk.rst
Labels: documentation

#172 Add services for Ocean Optics spectrometers
  catkit2/services/oceanoptics_spectrometer/oceanoptics_spectrometer.py
  catkit2/services/oceanoptics_spectrometer_sim/oceanoptics_spectrometer_sim.py
  catkit2/testbed/proxies/__init__.py
  catkit2/testbed/proxies/oceanoptics_spectrometer.py
  docs/index.rst
  docs/services/oceanoptics_spectrometer.rst
  environment.yml
Labels: hardware, collaborators
