Repository spacetelescope/catkit2, pull requests merged in 2024-05, with the labels that each got.

#196 Add round of service docs
  docs/index.rst
  docs/services/aimtti_plp.rst
  docs/services/allied_vision_camera.rst
  docs/services/empty_service.rst
  docs/services/ni_daq.rst
  docs/services/thorlabs_cld101x.rst
  docs/services/thorlabs_tsp01_sim.rst
  environment.yml
Labels: documentation

#192 Move simple simulator and model from hicat-package2 to catkit2
  catkit2/services/simple_simulator/simple_simulator.py
  catkit2/simulator/__init__.py
  catkit2/simulator/optical_model.py
  catkit2/simulator/simple_optical_model.py
  catkit2/simulator/simulator.py
  tests/test_optical_model.py
Labels: simulator

#205 Join temperature thread in AV cam service
  catkit2/services/allied_vision_camera/allied_vision_camera.py
Labels: bugfix

#200 Add services for Thorlabs motors using Kinesis
  catkit2/services/thorlabs_cube_motor_kinesis/thorlabs_cube_motor_kinesis.py
  catkit2/services/thorlabs_cube_motor_kinesis_sim/thorlabs_cube_motor_kinesis_sim.py
  catkit2/testbed/proxies/__init__.py
  catkit2/testbed/proxies/thorlabs_cube_motor_kinesis.py
  docs/index.rst
  docs/services/thorlabs_cube_motor_kinesis.rst
Labels: hardware, collaborators

#197 Updating service docs (Meiji)
  docs/services/allied_vision_camera.rst
  docs/services/hamamatsu_camera.rst
  docs/services/newport_picomotor.rst
  docs/services/web_power_switch.rst
  docs/services/zwo_camera.rst
  environment.yml
Labels: documentation

#209 Fix cube motor service doc file name in index.rst
  docs/index.rst
Labels: documentation
