Repository spacetelescope/catkit2, pull requests merged in 2025-07, with the labels that each got.

#339 Publish messages regarding service state and heartbeats.
  catkit2/testbed/testbed.py
  catkit2/tui/mtop.py
  catkit_core/Service.cpp
Labels: enhancement

#352 Use the MessageBroker to communicate Properties of Services.
  catkit2/bindings.cpp
  catkit2/services/zwo_camera/zwo_camera.py
  catkit_core/LocalMessageBroker.cpp
  catkit_core/LocalMessageBroker.h
  catkit_core/MessageBroker.cpp
  catkit_core/MessageBroker.h
  catkit_core/Property.cpp
  catkit_core/Property.h
  catkit_core/Service.cpp
  catkit_core/Service.h
  catkit_core/ServiceProxy.cpp
  catkit_core/ServiceProxy.h
  catkit_core/Uuid.cpp
  catkit_core/Uuid.h
  proto/service.proto
  tests/services/dummy_service/dummy_service.py
  tests/test_service.py
Labels: enhancement, needs all stakeholders

#361 Add power function mode to Thorlabs CLD laser diodes
  catkit2/services/thorlabs_cld101x/thorlabs_cld101x.py
Labels: hardware

#363 Adapt simulated CLD service
  catkit2/services/thorlabs_cld101x_sim/thorlabs_cld101x_sim.py
Labels: simulator

#366 Error in parameter name Hamamatsu
  catkit2/services/hamamatsu_camera/hamamatsu_camera.py
Labels: hardware, collaborators

#364 Hamamatsu temperature safety
  catkit2/services/hamamatsu_camera/hamamatsu_camera.py
  docs/services/hamamatsu_camera.rst
Labels: hardware, collaborators

#375 Add attribution instructions
  docs/acknowledging_catkit2.rst
  docs/index.rst
Labels: documentation

#373 Separate NKT SuperK services for EVO and FIANIUM
  catkit2/services/nkt_superk_evo/nkt_superk_evo.py
  catkit2/services/nkt_superk_evo_sim/nkt_superk_evo_sim.py
  catkit2/services/nkt_superk_fianium/nkt_superk_fianium.py
  catkit2/services/nkt_superk_fianium_sim/nkt_superk_fianium_sim.py
  catkit2/testbed/proxies/__init__.py
  catkit2/testbed/proxies/nkt_superk_evo.py
  catkit2/testbed/proxies/nkt_superk_fianium.py
  docs/index.rst
  docs/services/nkt_superk_evo.rst
  docs/services/nkt_superk_fianium.rst
  pyproject.toml
Labels: hardware

#377 Adapt simulated service of optical switch
  catkit2/services/optical_fiber_switch_sim/optical_fiber_switch_sim.py
Labels: simulator
