Repository spacetelescope/catkit2, pull requests merged in 2025-02, with the labels that each got.

#282 Enable high-resolution dither mode on BMC DMs
  catkit2/services/bmc_deformable_mirror_hardware/bmc_deformable_mirror_hardware.py
Labels: enhancement

#284 Add service_type input to BMC child class init
  catkit2/services/bmc_deformable_mirror_hardware/bmc_deformable_mirror_hardware.py
  catkit2/services/bmc_deformable_mirror_sim/bmc_deformable_mirror_sim.py
Labels: collaborators

#285 Remove old BMC services
  catkit2/services/bmc_dm/bmc_dm.py
  catkit2/services/bmc_dm_sim/bmc_dm_sim.py
  catkit2/testbed/proxies/__init__.py
  catkit2/testbed/proxies/bmc_dm.py
  docs/index.rst
  docs/services/bmc_dm.rst
  setup.py
  tests/config/services.yml
  tests/data/dm_mask.fits
  tests/services/dummy_dm_service/dummy_dm_service.py
  tests/test_dm_commands.py
Labels: refactor

#287 Add PCIe device id choice to DM startup
  catkit2/base_services/bmc_deformable_mirror.py
  catkit2/services/bmc_deformable_mirror_hardware/bmc_deformable_mirror_hardware.py
Labels: hardware, collaborators

#275 Move to `pyproject.toml` installation.
  .github/workflows/docs.yml
  .github/workflows/testing.yml
  CMakeLists.txt
  README.md
  benchmarks/CMakeLists.txt
  catkit2/CMakeLists.txt
  catkit2/bindings.cpp
  catkit_bindings/CMakeLists.txt
  catkit_core/CMakeLists.txt
  catkit_core/LoggingProxy.cpp
  catkit_core/Service.cpp
  catkit_core/ServiceProxy.cpp
  catkit_core/ServiceState.h
  catkit_core/Tensor.h
  catkit_core/TestbedProxy.cpp
  catkit_core/TestbedProxy.h
  catkit_core/Tracing.cpp
  catkit_core/Types.h
  catkit_core/cmake/CatkitCoreConfig.cmake.in
  docs/installation.rst
  environment.yml
  extern/download.sh
  pyproject.toml
  setup.py
Labels: enhancement, infrastructure

#283 Add trace interval 'processing frame' to Hamamatsu camera
  catkit2/services/hamamatsu_camera/hamamatsu_camera.py
Labels: collaborators
