Repository spacetelescope/catkit2, pull requests merged in 2025-06, with the labels that each got.

#335 Recreate shared memory for message broker if it already exists.
  catkit2/bindings.cpp
  catkit2/testbed/testbed.py
  catkit_core/SharedMemory.cpp
  catkit_core/SharedMemory.h
  environment.yml
Labels: bugfix

#331 Add ArrayView type for message broker.
  catkit2/bindings.cpp
  catkit_core/ArrayView.cpp
  catkit_core/ArrayView.h
  catkit_core/MessageBroker.cpp
  catkit_core/MessageBroker.h
  tests/test_message_broker.py
Labels: enhancement

#343 Add dark data stream to power meter
  catkit2/services/thorlabs_pm/thorlabs_pm.py
  catkit2/services/thorlabs_pm_sim/thorlabs_pm_sim.py
  docs/services/thorlabs_pm.rst
Labels: hardware

#346 Fix memory lifetime for Shareable objects.
  benchmarks/buddy_allocator.cpp
  benchmarks/event_latency.cpp
  benchmarks/hash_map.cpp
  benchmarks/hybrid_pool_allocator.cpp
  benchmarks/message_broker.cpp
  benchmarks/pool_allocator.cpp
  catkit2/bindings.cpp
  catkit_core/BuddyAllocator.cpp
  catkit_core/BuddyAllocator.h
  catkit_core/DataStream.cpp
  catkit_core/DataStream.h
  catkit_core/Event.cpp
  catkit_core/Event.h
  catkit_core/HashMap.cpp
  catkit_core/HashMap.h
  catkit_core/HybridPoolAllocator.cpp
  catkit_core/HybridPoolAllocator.h
  catkit_core/LocalMemory.cpp
  catkit_core/LocalMemory.h
  catkit_core/Memory.h
  catkit_core/MessageBroker.cpp
  catkit_core/MessageBroker.h
  catkit_core/PoolAllocator.cpp
  catkit_core/PoolAllocator.h
  catkit_core/Shareable.cpp
  catkit_core/Shareable.h
  catkit_core/SharedMemory.cpp
  catkit_core/SharedMemory.h
  catkit_core/StructStream.cpp
  catkit_core/StructStream.h
  catkit_core/StructStream.inl
  catkit_core/TestbedProxy.cpp
Labels: bugfix

#350 Add tests for process stats.
  catkit2/bindings.cpp
  tests/test_process_stats.py
Labels: enhancement

#338 Add Phasics SID4 Service to Catkit2
  catkit2/services/phasics_cam/phasics_cam.py
  catkit2/services/phasics_cam_sim/phasics_cam_sim.py
  catkit2/testbed/testbed.py
  docs/index.rst
  docs/services/phasics_cam.rst
  pyproject.toml
Labels: enhancement

#357 logging INFO CYAN instead of BLUE
  catkit2/testbed/logging.py
Labels: enhancement
