Repository spacetelescope/catkit2, pull requests merged in 2025-03, with the labels that each got.

#289 Add shareable base class
  benchmarks/free_list_allocator.cpp
  benchmarks/hash_map.cpp
  benchmarks/pool_allocator.cpp
  catkit2/bindings.cpp
  catkit_core/DataStream.cpp
  catkit_core/DataStream.h
  catkit_core/Event.cpp
  catkit_core/Event.h
  catkit_core/EventBase.h
  catkit_core/EventBase.inl
  catkit_core/EventConditionVariable.inl
  catkit_core/EventFutex.inl
  catkit_core/EventSemaphore.inl
  catkit_core/EventSpinLock.inl
  catkit_core/FreeListAllocator.cpp
  catkit_core/FreeListAllocator.h
  catkit_core/HashMap.cpp
  catkit_core/HashMap.h
  catkit_core/PoolAllocator.cpp
  catkit_core/PoolAllocator.h
  catkit_core/Service.cpp
  catkit_core/Shareable.cpp
  catkit_core/Shareable.h
  catkit_core/Shareable.inl
  catkit_core/SharedMemory.cpp
  catkit_core/SharedMemory.h
Labels: enhancement

#294 Add line to installation.rst describing how to increase ulimit
  README.md
  docs/installation.rst
Labels: documentation

#299 Fix compiler warning message.
  catkit_core/ServiceProxy.cpp
Labels: bugfix

#298 Doc cleanup
  README.md
  docs/installation.rst
  docs/services/accufiz_interferometer.rst
  docs/services/aimtti_plp.rst
  docs/services/bmc_deformable_mirror.rst
  docs/services/deformable_mirror.rst
  docs/services/newport_xps_q8.rst
  docs/services/thorlabs_cube_motor_kinesis.rst
Labels: documentation

#297 Refactor of Shareable states using a streaming specification.
  CMakeLists.txt
  benchmarks/free_list_allocator.cpp
  benchmarks/hash_map.cpp
  benchmarks/pool_allocator.cpp
  catkit2/CMakeLists.txt
  catkit_core/DataStream.cpp
  catkit_core/DataStream.h
  catkit_core/Event.cpp
  catkit_core/Event.h
  catkit_core/FreeListAllocator.cpp
  catkit_core/FreeListAllocator.h
  catkit_core/HashMap.cpp
  catkit_core/HashMap.h
  catkit_core/PoolAllocator.cpp
  catkit_core/PoolAllocator.h
  catkit_core/Shareable.cpp
  catkit_core/Shareable.h
  catkit_core/Shareable.inl
  catkit_core/SharedMemory.cpp
  catkit_core/SharedMemory.h
  catkit_core/StructStream.h
Labels: refactor

#300 Fix formatting in installation instructions
  docs/installation.rst
Labels: documentation
