Repository spacetelescope/catkit2, pull requests merged in 2025-05, with the labels that each got.

#272 Add a shared-memory message broker.
  CMakeLists.txt
  benchmarks/CMakeLists.txt
  benchmarks/buddy_allocator.cpp
  benchmarks/hybrid_pool_allocator.cpp
  benchmarks/message_broker.cpp
  benchmarks/pool_allocator.cpp
  benchmarks/uuid_generator.cpp
  catkit2/bindings.cpp
  catkit_core/BuddyAllocator.cpp
  catkit_core/BuddyAllocator.h
  catkit_core/ConcurrentVector.h
  catkit_core/ConcurrentVector.inl
  catkit_core/CudaSharedMemory.h
  catkit_core/DataStream.cpp
  catkit_core/DataStream.h
  catkit_core/Event.cpp
  catkit_core/Event.h
  catkit_core/EventBase.h
  catkit_core/EventBase.inl
  catkit_core/EventConditionVariable.inl
  catkit_core/EventSemaphore.inl
  catkit_core/EventSpinLock.inl
  catkit_core/FreeListAllocator.cpp
  catkit_core/FreeListAllocator.h
  catkit_core/HashMap.cpp
  catkit_core/HashMap.h
  catkit_core/HostName.cpp
  catkit_core/HostName.h
  catkit_core/HybridPoolAllocator.cpp
  catkit_core/HybridPoolAllocator.h
  catkit_core/LocalMemory.cpp
  catkit_core/LocalMemory.h
  catkit_core/Memory.h
  catkit_core/MessageBroker.cpp
  catkit_core/MessageBroker.h
  catkit_core/PoolAllocator.cpp
  catkit_core/PoolAllocator.h
  catkit_core/RefCounter.h
  catkit_core/ServiceProxy.h
  catkit_core/Shareable.cpp
  catkit_core/Shareable.h
  catkit_core/SharedMemory.cpp
  catkit_core/SharedMemory.h
  catkit_core/TestbedProxy.cpp
  catkit_core/Util.h
  catkit_core/Util.inl
  catkit_core/Uuid.cpp
  catkit_core/Uuid.h
  tests/test_allocator.py
  tests/test_event.py
  tests/test_message_broker.py
  tests/test_tracing.py
  tests/test_uuid.py
Labels: enhancement

#313 Add an mtop utility.
  catkit2/tui/__init__.py
  catkit2/tui/mtop.py
  pyproject.toml
Labels: enhancement

#317 Fix power setting in simulated NKT and MCLS1 Services
  catkit2/services/nkt_superk_sim/nkt_superk_sim.py
  catkit2/services/thorlabs_mcls1_sim/thorlabs_mcls1_sim.py
Labels: simulator, bugfix

#320 Move lock upstream to the deformable mirror base class.
  catkit2/base_services/deformable_mirror.py
  catkit2/services/bmc_deformable_mirror_hardware/bmc_deformable_mirror_hardware.py
  catkit2/services/bmc_deformable_mirror_sim/bmc_deformable_mirror_sim.py
Labels: bugfix

#328 Hack for BMMC DMs on HiCAT with PCIe device setting
  catkit2/services/bmc_deformable_mirror_hardware/bmc_deformable_mirror_hardware.py
Labels: hack

#310 Add a benchmark for latency for events.
  benchmarks/CMakeLists.txt
  benchmarks/event_latency.cpp
  catkit2/bindings.cpp
  catkit_core/DataStream.cpp
  catkit_core/Event.cpp
  catkit_core/Event.h
  catkit_core/EventBase.h
  catkit_core/EventBase.inl
  catkit_core/EventConditionVariable.inl
  catkit_core/EventSpinLock.inl
  catkit_core/MessageBroker.cpp
  tests/test_event.py
Labels: enhancement, bugfix

#332 updates to shared memory tests
  tests/test_shared_memory.py
Labels: enhancement, tests
